feat_order_5
J1P3ter/Astraphe pull request #42
Opened 2024-10-13 19:19 UTC by lossol1

## 📌 Related Issue
> 이슈 번호를 기재 해주세요 (ex) #0)

- 
 Feat order 5

## 📢 Changes
> 변경 사항을 기재 해주세요

- 
order crud 및 Kafka 설정 

## 📸 Test
> 테스트 결과를 공유 해주세요

- 

## 📢 Check List
> 체크 리스트를 확인하고 완료되면 체크 해주세요

- [ ] 테스트를 완료 하셨나요?
- [ ] Source Branch & Target Branch 확인 하셨나요??
- [ ] 코드 리뷰 요청을 하셨나요??

## 🚀 참고 자료
> 참고 자료가 있다면 첨부 해주세요
-

2024-10-14 02:06 UTC, lukeydokey requested changes

2024-10-14 02:06 UTC, lukeydokey commented on order-server/src/main/java/com/j1p3ter/orderserver/domain/order/Order.java
softDelete가 있기때문에 delete 메서드를 만들 필요가 없습니다

2024-10-14 02:06 UTC, lukeydokey commented on order-server/src/main/java/com/j1p3ter/orderserver/infrastructure/kafka/messaging/ProductEventProducer.java
send할때 헤더에 X-USER-ID도 담아야합니다

2024-10-14 03:49 UTC, lukeydokey requested changes

2024-10-14 03:49 UTC, lukeydokey commented on order-server/src/main/java/com/j1p3ter/orderserver/infrastructure/kafka/messaging/ProductEventProducer.java
이거 지우시거나 create에 있는 로직을 여기에 가져오거나 해야할것같아요

2024-10-15 05:09 UTC, VoiceofSiren approved these changes
확인했습니다.

2024-10-15 05:35 UTC, merged